import type { APIRequestContext, Page } from "@playwright/test"

/**
 * Shared helpers for the v3 e2e harness. Kept dependency-free (no XML/perf
 * libraries) so the harness only ever needs `@playwright/test` and
 * `@axe-core/playwright` — see the worktree edit allowlist in the task brief.
 */

/* -------------------------------------------------------------------------- */
/* Console errors                                                             */
/* -------------------------------------------------------------------------- */

export interface ConsoleErrorCollector {
  /** Mutated in place as errors arrive — read `.length` / contents any time. */
  errors: string[]
}

/**
 * Attaches `console` (error level only) and `pageerror` listeners to `page`
 * and returns a live-updating collector. Attach before navigating.
 */
export function collectConsoleErrors(page: Page): ConsoleErrorCollector {
  const collector: ConsoleErrorCollector = { errors: [] }

  page.on("console", (msg) => {
    if (msg.type() === "error") {
      collector.errors.push(msg.text())
    }
  })

  page.on("pageerror", (err) => {
    collector.errors.push(err.message)
  })

  return collector
}

/* -------------------------------------------------------------------------- */
/* Sitemap                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Fetches `/sitemap.xml` and extracts every `<loc>` entry. Regex-based on
 * purpose: the sitemap is generated by `next-sitemap`'s successor,
 * `app/sitemap.ts`, so it is always well-formed, and pulling in an XML parser
 * just for this would be a dependency the harness doesn't otherwise need.
 */
export async function readSitemapUrls(
  request: APIRequestContext,
  baseURL: string
): Promise<string[]> {
  const res = await request.get(`${baseURL}/sitemap.xml`)
  if (!res.ok()) {
    throw new Error(`GET /sitemap.xml returned ${res.status()}`)
  }
  const body = await res.text()
  const matches = [...body.matchAll(/<loc>([^<]+)<\/loc>/g)]
  return matches.map((m) => m[1].trim())
}

/** `https://mladenruzicic.com/work/foo` → `/work/foo`, relative to `base`. */
export function toPathname(url: string, base: string): string {
  return new URL(url, base).pathname
}

/* -------------------------------------------------------------------------- */
/* Cumulative Layout Shift                                                    */
/* -------------------------------------------------------------------------- */

declare global {
  interface Window {
    __e2eCls?: number
    __e2eLcp?: { startTime: number; size: number } | null
  }
}

/**
 * Installs a `layout-shift` PerformanceObserver before any page script runs,
 * accumulating every shift that didn't follow recent user input. Call before
 * `page.goto`.
 */
export async function installClsObserver(page: Page): Promise<void> {
  await page.addInitScript(() => {
    window.__e2eCls = 0
    try {
      const po = new PerformanceObserver((list) => {
        for (const entry of list.getEntries() as unknown as {
          hadRecentInput: boolean
          value: number
        }[]) {
          if (!entry.hadRecentInput) {
            window.__e2eCls = (window.__e2eCls ?? 0) + entry.value
          }
        }
      })
      po.observe({ type: "layout-shift", buffered: true })
    } catch {
      // layout-shift not supported in this engine; leave __e2eCls at 0.
    }
  })
}

/** Reads the CLS value accumulated by {@link installClsObserver}. */
export async function getCls(page: Page): Promise<number> {
  return page.evaluate(() => window.__e2eCls ?? 0)
}

/* -------------------------------------------------------------------------- */
/* Largest Contentful Paint                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Installs a `largest-contentful-paint` PerformanceObserver before any page
 * script runs. LCP candidates can still update after this read, but the final
 * entry (once painting settles) is what budgets.spec.ts and motion.spec.ts
 * compare other timings against. Call before `page.goto`.
 */
export async function installLcpObserver(page: Page): Promise<void> {
  await page.addInitScript(() => {
    window.__e2eLcp = null
    try {
      const po = new PerformanceObserver((list) => {
        const entries = list.getEntries() as unknown as {
          startTime: number
          size: number
        }[]
        const last = entries[entries.length - 1]
        if (last) {
          window.__e2eLcp = { startTime: last.startTime, size: last.size }
        }
      })
      po.observe({ type: "largest-contentful-paint", buffered: true })
    } catch {
      // largest-contentful-paint not supported in this engine.
    }
  })
}

/** Reads the last LCP candidate observed by {@link installLcpObserver}. */
export async function getLcp(
  page: Page
): Promise<{ startTime: number; size: number } | null> {
  return page.evaluate(() => window.__e2eLcp ?? null)
}

/* -------------------------------------------------------------------------- */
/* Resource timing                                                            */
/* -------------------------------------------------------------------------- */

export interface ResourceTiming {
  name: string
  startTime: number
  /** Compressed, over-the-wire byte count; 0 for cached/opaque responses. */
  transferSize: number
  initiatorType: string
}

/** All `PerformanceResourceTiming` entries recorded so far in `page`. */
export async function getResourceTimings(page: Page): Promise<ResourceTiming[]> {
  return page.evaluate(() =>
    performance.getEntriesByType("resource").map((entry) => {
      const r = entry as PerformanceResourceTiming
      return {
        name: r.name,
        startTime: r.startTime,
        transferSize: r.transferSize,
        initiatorType: r.initiatorType,
      }
    })
  )
}

/* -------------------------------------------------------------------------- */
/* Live request tracking                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Attaches a `request` listener that records every request URL containing
 * `substring`. Node-side (as opposed to {@link getResourceTimings}), so it
 * also catches requests the page's own performance timeline might miss (e.g.
 * ones aborted before completion). Attach before navigating.
 */
export function trackRequestsMatching(page: Page, substring: string): string[] {
  const urls: string[] = []
  page.on("request", (req) => {
    if (req.url().includes(substring)) urls.push(req.url())
  })
  return urls
}
