name: Code check

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    name: Lint, typecheck, build
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm typecheck

      - run: pnpm build
